# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ofli/.local/lib/python3.8/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/ofli/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ofli/projects/llama2c_in_flutter/llama2c_package/llama2.c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ofli/projects/llama2c_in_flutter/llama2c_package/llama2.c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ofli/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ofli/.local/lib/python3.8/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ofli/projects/llama2c_in_flutter/llama2c_package/llama2.c/CMakeFiles /home/ofli/projects/llama2c_in_flutter/llama2c_package/llama2.c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ofli/projects/llama2c_in_flutter/llama2c_package/llama2.c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named llama2c_library

# Build rule for target.
llama2c_library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llama2c_library
.PHONY : llama2c_library

# fast build rule for target.
llama2c_library/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama2c_library.dir/build.make CMakeFiles/llama2c_library.dir/build
.PHONY : llama2c_library/fast

#=============================================================================
# Target rules for targets named llama2c_exe

# Build rule for target.
llama2c_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llama2c_exe
.PHONY : llama2c_exe

# fast build rule for target.
llama2c_exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama2c_exe.dir/build.make CMakeFiles/llama2c_exe.dir/build
.PHONY : llama2c_exe/fast

run.o: run.c.o
.PHONY : run.o

# target to build an object file
run.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama2c_library.dir/build.make CMakeFiles/llama2c_library.dir/run.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama2c_exe.dir/build.make CMakeFiles/llama2c_exe.dir/run.c.o
.PHONY : run.c.o

run.i: run.c.i
.PHONY : run.i

# target to preprocess a source file
run.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama2c_library.dir/build.make CMakeFiles/llama2c_library.dir/run.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama2c_exe.dir/build.make CMakeFiles/llama2c_exe.dir/run.c.i
.PHONY : run.c.i

run.s: run.c.s
.PHONY : run.s

# target to generate assembly for a file
run.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama2c_library.dir/build.make CMakeFiles/llama2c_library.dir/run.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama2c_exe.dir/build.make CMakeFiles/llama2c_exe.dir/run.c.s
.PHONY : run.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... llama2c_exe"
	@echo "... llama2c_library"
	@echo "... run.o"
	@echo "... run.i"
	@echo "... run.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

